# 13. 예외 처리

* 예외: 복구가 가능한 오류
* 에러: 복구가 불가능한 오류



## 예외 처리

* 프로그램 실행 중 발생한 에러 --> 프로그램 실행 종료(디폴트)
* 예외 발생을 감지하고 복구하는 방법

```python
try:
    실행할 명령
except 예외 as 변수:
    오류 처리문
else:
    예외가 발생하지 않을 때의 처리
```

* 예외의 종류
  * NameError : not defined
  * ValueError : str<->int
  * ZeroDivisionError :    /0
  * IndexError : 리스트 인덱스
  * TypeError  : list<->dict
* raise: 개발자에 의해 임의로 예외를 발생시킴
* finally: 예외 발생 여부와 상관없이 항상 호출



### ex01

점수를 입력받아 정수면 점수를 출력, 아니면 예외 메세지 출력

```python
while True:
    str=input('점수를 입력하세요: ')

    try:
        score = int(str)
        print('입력한 점수:',score)
        break
    except:
        print('예외가 발생했습니다.')

print('작업완료')
```

### ex02

점수를 입력받아 ValueError면 형식 오류 메세지, IndexError면 인덱스 오류 메세지

```python
str='89'

try:
    score = int(str)
    print(score)
    a=str[5]
except ValueError:
    print('점수의 형식이 잘못되었습니다.')
except IndexError:
    print('첨자 범위를 벗어났습니다.')

print('작업완료')
```

### ex03

```python
def chat():
    try:
        print('네트워크 접속')
        a=2/0
        print('네트워크 통신 수행')
    except:
        print('네트워크 에러 발생')
    finally:    # try 블럭이나 except 블럭을 벗어날때 실행
        print('접속 해제')
    print('======================')

print('통신을 시작합니다')
chat()
print('통신이 끝났습니다.')
```

finally를 사용하는 이유는

try 블럭에 return값이 있다면 

try 블럭을 벗어나면서 

`chat()`함수 아래부분의 `print('======================')`코드를 읽지 않음



## 자원의 정리

### assert

* assert 조건, 메세지
* 조건이 True이면 통과,
* False이면 메세지를 가지는 예외 발생